### ISSUE TITLE
Second send of coins sent did not broadcast, Any help?

### ISSUE THREAD

**Issue by chambam** [markblundeberg/coinsplitter#12]
Hi Mark,

I sent a small test of coins to Kraken from the ledger nano I had your coinsplitter attached. It worked perfectly once received in the Kranken exchange the coins were split, I felt comfortable to send all and then the BSV coins did not turn up in the 2nd transaction, below is what Kraken and Ledger support both said. I am at loss to know what to do. Could you offer any guidance, please?

Thank you for reaching out again,
Your funds are not lost, they are still on the sending address you can check it yourself on the BSV explorer,
This is the address for your convenience qq0qejgq33n7d38xtjnmyy0wpyp50j5r9sr8dtwu7k.
We split the coins when they are included on the transaction just like the first deposit.
as I said before your wallet either didn't broadcast it to the BSV chain or that the transaction wasn't replay-able. If it is replay-able you will need to find a tool to broadcast the transaction on or alternatively import your keys into a BSV wallet and send the tokens manually. 
The BSV funds are still resting on the sending address.

**Comment by markblundeberg** [comment]
Hi @chambam sorry for the delay, it seems I missed the notification.

If you split your own coins (using my tool, or otherwise) the idea is that you don't need the exchange to split them for you.

However it means you now have separate balances of BCH and BSV on your wallets, and you need to connect to a BSV Electron Cash server to interact with the BSV coins.

**Comment by markblundeberg** [comment]
* Tools | Network
* second tab
* `satoshi.vision.cash` port 50002

That should bring your wallet onto an SV server, and from there you can move your BSV coins around like normal.

**Comment by chambam** [comment]
Mark,
Thank you for the help. I presume your directions are related to the
electron cash wallet? For some reason it is no longer on my computer, just
download it again and follow your instructions?

Below is what Kraken sent to me, does this change anything?
Thank you in advance!

*Hi Jonathan,*



*I understand your situation, I have made an exception for you, went ahead
and checked for you and found out your transaction is not replayable, since
you have mix coins on the same wallet, the transaction originated for this
2 addresses of which one of them does not hold any BSV funds, please go
ahead and check it yourself on a BSV
explorer: qzvrczcw3szlwzkkvm3g9svmxqsuj66qfq3aax26w4 -> 0.00000000
BSVqq0qejgq33n7d38xtjnmyy0wpyp50j5r9sr8dtwu7k -> 2.66732462 BSV*

*What you need to do now is import your keys into a BSV wallet and send the
tokens manually or wait until your wallet supports BSV and then you can
send them. (always test with the smallest amount to be sure)*

*Since we aren't affiliated with any BSV wallet clients we cannot make any
suggestions or help in this process, however you can try finding some help
in forums like reddit. (Never give your private keys to anybody)*

*To answer your second question, your coins in kraken now have nothing to
do with the ones in your wallet, so you are free to trade them as you wish,
it will not be affecting your BSV coins on your personal wallet.*

*Hope it helps thank you for using kraken!*

**Comment by markblundeberg** [comment]
Yes, as they say the BSV coins are still on your wallet: https://bchsvexplorer.com/address/qq0qejgq33n7d38xtjnmyy0wpyp50j5r9sr8dtwu7k

And yes if you install Electron Cash you can spend those BSV coins provided you direct it to a Bitcoin SV server, via the Network dialog.

**Comment by chambam** [comment]
Sorry Mark, plz see image attached. I re-installed the electron splitting
wallet, used the same seed. The balance shows as BCH can I now send that to
the Kraken exchange? is that my funds back in my wallet?

**Comment by markblundeberg** [comment]
I don't see an image.

To know whether you're looking at a BCH balance or a BSV balance, you have to check the network dialog and see which kind of server you are connected to.

**Comment by chambam** [comment]
I have attached an image with sever showing top left and is

   - satoshi.vision.cash port 50002

the balance is shown in  BCH. bottom left of screenshot.

I am simply not sure if this is correct and save to send to the exchange?

**Comment by markblundeberg** [comment]
It looks like when you include an attachment by email, it doesn't work. Rather, to 

But yes, that server is a BSV server. As you said before you already emptied this wallet on BCH so there is no way that the balance you're seeing is BCH. Sounds like it is definitely safe.

In any case, if you are sending to Kraken then even if you make a mistake, they will split your coins for you. So it sounds like no possibility to lose funds by depositing there.

**Comment by chambam** [comment]
I am about to send the BSV on the SV server to Kraken' s BSV address.

The wallet still shows BCH balance, rather than attach an image you can't
open, I have put the image on dropbox with link here:
https://www.dropbox.com/s/96mlo7wrz1bexoa/adddress.jpeg?dl=0

SO this is all ok to hit send?

**Comment by markblundeberg** [comment]
Yeah, it's OK!

It will always show "BCH" because that's how it's programmed. Electron Cash doesn't actually know whether it's on BCH-ABC chain or BCH-SV chain, it just follows whatever the server tells it and thinks of it as "BCH" regardless.

**Comment by chambam** [comment]
Mark, I am nearly there thanks to your help!

Unfortunately the sending address I input and the address to be confirmed
on my nano are different? any idea? see below

Please link https://www.dropbox.com/s/ltcn1nvnijlo5c3/sending.jpg?dl=0
<https://t.yesware.com/tt/1e1f10b45f47ec215420a4b201948f6a038e1f8a/c6df3784f2794e58f3f6a4d4603d0c75/c287d7a63b4b88c816d95a25b551d909/www.dropbox.com/s/ltcn1nvnijlo5c3/sending.jpg?dl=0>

and attached

**Comment by markblundeberg** [comment]
Hey @chambam no worries, it's good to check these things to make sure. Look in the bottom right of your Electron Cash window to switch addresses from CashAddr to Legacy. Then you can view those transaction details in legacy format.

![index](https://user-images.githubusercontent.com/36528214/49622930-6a56be80-f980-11e8-9860-b51e4428a038.jpeg)

**Comment by chambam** [comment]
That worked mark. I confirmed the address on my nano, but then the nano
went to transaction 2 and I do not know what transaction 2 is our the
address so I have to cancel and that then cancels all transactions, what
do? sorry!

screen shot link and attached
https://www.dropbox.com/s/mqb6kn433ji8jut/transaction.jpg?dl=0

**Comment by markblundeberg** [comment]
Looks like that screenshot link doesn't work ...

Also I've never used a Ledger before so I don't know what "transaction 2" would mean.... sorry.

**Comment by chambam** [comment]
try below now. I connect my ledger to your wallet presumed I had to,
anyway see link for screenshot below from your cash wallet

https://www.dropbox.com/s/ayfso9ys01u7q1f/transaction.jpg?dl=0

**Comment by markblundeberg** [comment]
Ah OK I see -- it is one transaction but there are two outputs.

According to electron cash, the second output is going to a change address of that wallet (this is why it's colored yellow). I'm surprised the Ledger doesn't realize that.

**Comment by chambam** [comment]
omg sc-fi.....so I should confirm both transactions? even though the 2nd I
have no clue why it is there

**Comment by KMFDM29** [comment]
Hello! Please tell me, do you think that sending BСН to split coins on KRAKEN is safe? Is it easier than safer than the method you provided?

**Comment by chambam** [comment]
I did this and worked for me. However, I sent a second transaction and the
BSV coins ended up stuck on the sending address which I am still dealing
with. I cannot say why that happened and though it did happen I would say
sending to Kraken to split is safe.

**Comment by KMFDM29** [comment]
I never dealt with exchanges.I only keep coins in my wallet.I'm afraid of splitting myself.If you do the exchange as soon as they return back to split? If SV can be a problem,then BCH will be sent anyway?I just don't want to lose everything.
