### ISSUE TITLE
AttributeError when trying to split coins

### ISSUE THREAD

**Issue by anotheraccountomg** [markblundeberg/coinsplitter#14]
I get stuck on step #2, when connecting my nano S, it gives me an error -- see attached file. "NoneType" object has no attribute "handler"
<img width="302" alt="ec error" src="https://user-images.githubusercontent.com/46054012/50354032-b91f5f00-050f-11e9-8fda-a1b52ffabdad.PNG">

https://support.ledger.com/hc/en-us/articles/360012270054-Safely-claim-Bitcoin-Cash-SV

**Comment by markblundeberg** [comment]
Can you try out the newest version I just released? https://github.com/markblundeberg/coinsplitter/releases/tag/3.3.3CS

**Comment by anotheraccountomg** [comment]
I will try that, thanks for your help!

**Comment by markblundeberg** [comment]
Yes, CDS is the one you want.

(MUL approach is for making a splitter that works the other way, i.e., making transactions that can only exist on SV chain.)
