### ISSUE TITLE
import existing seed phrase fail, and confirm new seed phrase fail

### ISSUE THREAD

**Issue by standarduseraccount** [markblundeberg/coinsplitter#15]
When importing a seed phrase from another wallet it won't allow you to click the "Next" button, and when confirming a new seed phrase it won't let you click the "Next" button.

**Comment by markblundeberg** [comment]
Make sure to open Options from the seed dialog and enable BIP39, if it's from a non-electron-cash wallet

**Comment by standarduseraccount** [comment]
It's when setting up an Electron Cash wallet specifically with this .exe coin splitter download for Windows. There are two issues. When trying to import from the Bitcoin.com wallet's seed phrase during electron cash setup right after downloading this coin splitter implementation the "Next" button is inactive. Secondarily the next button will also not display when confirming a new seed phrase during the setup process, this is right after creating a new seed phrase during setup.

**Comment by markblundeberg** [comment]
Hmmmm that is very strange.

I wonder if there is some sort of keyboard / unicode stuff going on.

I wonder, is it possible for you to generate a new seed phrase, type it in to the dialog, see it fail, and then copy+paste exactly what is in the textbox, into a comment here? Obviously don't share any seed that actually has funds on it, only a throwaway new one.

Also, which precise version is this? I have [5 different releases](https://github.com/markblundeberg/coinsplitter/releases) so I'd like to try to exactly reproduce..

**Comment by standarduseraccount** [comment]
I just tried restarting the program and making a new seed phrase again and the next button worked this time, but the actual import of the Bitcoin.com wallet seed phrase did not show the next button still. So I tried clicking Options and Bip39 like you suggested, and the next button worked, but the wallet doesn't show any funds. I'm wondering if I should use a different derivation path. My funds are still showing in the Bitcoin.com wallet, however. Using Electron-Cash-3.3.4CS.exe. I haven't updated the Bitcoin.com wallet since the most recent fork, though.

I'd think you could be right about the keyboard, too. It's a British style keyboard using USA standard keyboard options on Windows 10. So maybe it's just my setup somehow reading the phrase as a different language or something.

**Comment by markblundeberg** [comment]
OK, you're almost there. :-) What's missing is likely that you put the wrong derivation path, but maybe you need "extend this seed with custom words" too.

Try following these instructions: https://docs.google.com/document/d/1cjb49zzT_3d00aOYjD7NoYn6Ws9punhSJjFZIjgo-hk/edit#heading=h.yudueezgdl57

**Comment by standarduseraccount** [comment]
Works on derivation path m/44'/0'/0'

I noticed it's pretty important to pay attention if your server is set automatically, it can switch between BSV and BCH any time the internet connection changes.

**Comment by markblundeberg** [comment]
Great to hear! Yes, that's a good point about the automatic server.
