### ISSUE TITLE
Getting AttributeError when trying to split coins

### ISSUE THREAD

**Issue by nforss** [markblundeberg/coinsplitter#6]
I'm getting the following error when trying to split my coins. Please advice.

![image](https://user-images.githubusercontent.com/846928/48691553-9da4f980-ebdb-11e8-8bc6-0e78d4732ee4.png)

**Comment by markblundeberg** [comment]
OK, this is the same as #7 ... 

For now I recommend you can follow [https://github.com/markblundeberg/coinsplitter_checkdatasig/blob/master/doc/coinsplitter_user_guide.md#splitting-other-wallets-hardware--cold-watching-only--non-electron-cash](these steps) as a backup plan.

Or you can wait for me to fix bug, which I should get around to in next couple of days.

**Comment by rolfschr** [comment]
I have the same issue. However, I am able to open the split dialog via right-click on any of the receiving addresses as described in the readme [https://github.com/markblundeberg/coinsplitter_checkdatasig/blob/master/doc/coinsplitter_user_guide.md#from-address-list](https://github.com/markblundeberg/coinsplitter_checkdatasig/blob/master/doc/coinsplitter_user_guide.md#from-address-list)

**Comment by markblundeberg** [comment]
Fixed in 52a1b53
