### ISSUE TITLE
Doesn't run on MacOS High Sierra

### ISSUE THREAD

**Issue by deludologist** [markblundeberg/coinsplitter#8]
I am trying to run this on High Sierra, and can't get it to even start. When I click on the icon, I get a bobbing icon in my dock, and then it just quits.

**Comment by ekuester** [comment]
Try starting it from terminal, in most cases there will be some helpful output before the program dies.

**Comment by deludologist** [comment]
Unfortunately not. I tried `open Electron-Cash.app` and `sudo open Electron-Cash.app`, but it just goes back to prompt.

**Comment by ekuester** [comment]
OK. Is it an option for you to compile the program yourself? The instructions are relatively clear: Run the script and you are done ;-) Surely I know that it is not that just simple.
Perhaps I could have a look on the problem. In the moment my Mac had only 10.12 (and I will not change the OS) and most the time I am working under Linux with elecron-cash fully functional, so I can not promise anything.

**Comment by markblundeberg** [comment]
Is this still an issue in the latest release? https://github.com/markblundeberg/coinsplitter/releases/tag/3.3.3CS

I really don't know anything about MacOS so I can't be of much help.

**Comment by markblundeberg** [comment]
Seems to be related to upstream bug https://github.com/Electron-Cash/Electron-Cash/issues/1066 or https://github.com/Electron-Cash/Electron-Cash/issues/955 perhaps... closing for now.

**Comment by cculianu** [comment]
One other user, Manufoy reported a similar problem on Mojave.  He would get a SEGFAULT in libssl before the Python process was even fully initialized.  Here is the issue in the EC regular git: 

https://github.com/Electron-Cash/Electron-Cash/issues/1066

We normally build Electron Cash (and CoinSplitter) on "El Capitan" which works backwards and forwards with the most MacOS versions.  

But for somer reason for this 1 guy it wouldn't run. I ended up building it a second time just for him on High Sierra -- and it ran fine.

I can give Mark 2 sets of binaries on the next version-- 1 for El Capitan and 1 for HighSierra+.

This is not a real fix but a workaround.

**Comment by markblundeberg** [comment]
@cculianu made a new fix version that should work in both macos -- let us know if there are still issues. https://github.com/markblundeberg/coinsplitter/releases/tag/3.3.4CS
